<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="prefix length width height mass wheel_radius wheel_pos_z inner_width">
    <link name="base_footprint${prefix}"/>
    
    <link name="base_link${prefix}">
      <visual>
        <origin xyz="0 0 -0.006" rpy="0 0 0"/>
        <geometry>
          <!-- <box size="${length} ${inner_width} ${height}"/> -->
          <mesh filename="file://$(find linorobot2_description)/urdf/meshes/capstone_mesh_FRU.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 ${base_z_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.022 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(4/12) * mass * ((width * width) + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(4/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(4/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>

    <gazebo reference="base_link${prefix}">  
      <visual>
        <material>
          <ambient>1 1 1 1.0</ambient>  
          <diffuse>1 1 1 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.5 0.5 0.5 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <joint name="base_to_footprint${prefix}" type="fixed">
      <parent link="base_footprint${prefix}"/>
      <child link="base_link${prefix}"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>