<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="diff_drive_controller" params="prefix namespace remap wheel_separation wheel_radius wheel_torque">
    <gazebo>
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <argument>odom:=odom/unfiltered</argument>
          <namespace>${namespace}</namespace>
          <xacro:if value="${remap}" >
            <remapping>/tf:=tf</remapping>
          </xacro:if>
        </ros>
        <robot_base_frame>base_footprint${prefix}</robot_base_frame>
        <updateRate>20</updateRate>
        <left_joint>left_wheel_joint${prefix}</left_joint>
        <right_joint>right_wheel_joint${prefix}</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
        <wheel_torque>${wheel_torque}</wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>
        <publish_odom>true</publish_odom>
        <publish_odom_tf>false</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>
        <odometry_frame>odom${prefix}</odometry_frame>

        <mu1>0.5</mu1>
        <mu2>0.5</mu2>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>